project:
  type: website
  output-dir: site

website:
  title: "BnBInsight"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: tutorial.qmd
        text: Tutorial
      - href: report.qmd
        text: Report

format:
  html:
    theme: cosmo
    toc: true
