project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - tutorial.qmd
    - report.qmd

website:
  title: "BnBInsight"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: tutorial.qmd
        text: Tutorial
      - href: report.qmd
        text: Report
    right:
      - icon: github
        href: https://github.com/mbgardin/BnBInsight
        text: GitHub
      - icon: box-arrow-up-right
        href: https://bnbinsight.streamlit.app/
        text: Streamlit
      - icon: box-seam
        href: https://pypi.org/project/bnbinsight/
        text: PyPI

format:
  html:
    theme: cosmo
    toc: true
